name: CI/CD Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ] 
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest    
    env:
      NODE_VERSION: '20'

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm' 

      - name: Install Dependencies
        run: npm install

      - name: Build Project
        run: npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_branch: gh-pages
          publish_dir: ./build